CREATE OR REPLACE TRIGGER TG_PROGRAMAS_ACADEMICOS
BEFORE INSERT ON PROGRAMAS_ACADEMICOS
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_PROGRAMAS_ACADEMICOS.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/

CREATE OR REPLACE TRIGGER TG_CATEGORIAS_SOLICITUDES
BEFORE INSERT ON CATEGORIAS_SOLICITUDES
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_CATEGORIAS_SOLICITUDES.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/

CREATE OR REPLACE TRIGGER TG_TE_SOLICITUDES
BEFORE INSERT ON TIPOS_ESTADOS_SOLICITUDES
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_TE_SOLICITUDES.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/

CREATE OR REPLACE TRIGGER TG_TIPOS_DOCUMENTOS
BEFORE INSERT ON TIPOS_DOCUMENTOS
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_TIPOS_DOCUMENTOS.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/

CREATE OR REPLACE TRIGGER TG_TIPOS_USUARIOS
BEFORE INSERT ON TIPOS_USUARIOS
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_TIPOS_USUARIOS.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/

CREATE OR REPLACE TRIGGER TG_MATERIAS
BEFORE INSERT ON MATERIAS
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_MATERIAS.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/

CREATE OR REPLACE TRIGGER TG_SOLICITUDES
BEFORE INSERT ON SOLICITUDES
FOR EACH ROW
BEGIN	
	DECLARE 
		AUX INTEGER:= 0;
		BEGIN
			SELECT SQ_ID_SOLICITUDES.NEXTVAL INTO AUX FROM DUAL;
			:new.pk_id := AUX;
		END;
END;
/